name: Run Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # Runs every hour to keep it alive

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get bot code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start bot
        run: python main.py

          echo Add other actions to build,
          echo test, and deploy your project.

          env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

