name: Run Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get bot code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install -r requirements.txt || true

      - name: Start bot
        run: python main.py  # Change this to your file name if needed
